name = "noroshi"
compatibility_date = "2023-12-01"
node_compat = true

[vars]
# MY_VAR = "my-variable"
GITHUB_ID = "YOUR_GITHUB_CLIENT_ID"
GITHUB_SECRET = "YOUR_GITHUB_CLIENT_SECRET"

AUTH_GOOGLE_CLIENT_ID = ""
AUTH_GOOGLE_CLIENT_SECRET = ""

STORAGE_TYPE = "r2"
ASSETS_URL = "https://your.r2.dev"

[dev]
port = 9000

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "your-bucket-images"

[[d1_databases]]
binding = "DB"
database_name = "your-db"
database_id = "XXXXX-XXXX-XXXX-XXXXX"
migrations_dir = "drizzle/"

# [ai]
# binding = "AI"